plugins:
  - jekyll-archives
  - jekyll/minibundle

highlighter: none
markdown: kramdown
tag_page_layout: tag_page
tag_page_dir: tag
jekyll-archives:
  enabled:
    - categories
  layout: tag_page
  permalinks:
    category: "/:name/"

sass:
  style: compressed

exclude:
  - node_modules
  - pnpm-lock.yaml
  - package.json
  - _assets/scripts/bundle.js
  - _assets/scripts/ni-api.js
  - _assets/scripts/speech-api.js
  - _assets/scripts/labs-vitals.js

name: All About the Code
description: Personal tech blog of Knut Haugen
url: https://blog.knuthaugen.no
